// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/ratelimiter/v1/ratelimiter.proto

package ratelimiterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckLimitRequest is the input for a single rate limit check.
type CheckLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tenant_id identifies the tenant whose plan to apply. Required.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// key is the client-specific identifier, e.g. "user:42" or "ip:1.2.3.4". Required.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// cost is the number of tokens to consume. Treated as 1 when zero or negative.
	Cost          int32 `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitRequest) Reset() {
	*x = CheckLimitRequest{}
	mi := &file_api_ratelimiter_v1_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitRequest) ProtoMessage() {}

func (x *CheckLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimiter_v1_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_ratelimiter_v1_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckLimitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckLimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckLimitRequest) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

// CheckLimitResponse is the result of a single rate limit check.
type CheckLimitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed reports whether the request is permitted.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// remaining is the estimated tokens/requests left in the current window.
	// -1 signals a degraded result: the store was unavailable and the request
	// was allowed under a fail-open policy. Callers should log/alert on -1.
	Remaining int64 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// retry_after_ms is how many milliseconds the caller should wait before
	// retrying. Zero when allowed=true.
	RetryAfterMs int64 `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	// reset_at_unix_ms is when the current window or token bucket fully resets,
	// as a Unix timestamp in milliseconds.
	ResetAtUnixMs int64 `protobuf:"varint,4,opt,name=reset_at_unix_ms,json=resetAtUnixMs,proto3" json:"reset_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLimitResponse) Reset() {
	*x = CheckLimitResponse{}
	mi := &file_api_ratelimiter_v1_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLimitResponse) ProtoMessage() {}

func (x *CheckLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimiter_v1_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_ratelimiter_v1_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckLimitResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckLimitResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckLimitResponse) GetResetAtUnixMs() int64 {
	if x != nil {
		return x.ResetAtUnixMs
	}
	return 0
}

var File_api_ratelimiter_v1_ratelimiter_proto protoreflect.FileDescriptor

const file_api_ratelimiter_v1_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"$api/ratelimiter/v1/ratelimiter.proto\x12\x0eratelimiter.v1\"V\n" +
	"\x11CheckLimitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x05R\x04cost\"\x9b\x01\n" +
	"\x12CheckLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x03R\fretryAfterMs\x12'\n" +
	"\x10reset_at_unix_ms\x18\x04 \x01(\x03R\rresetAtUnixMs2\xc0\x01\n" +
	"\vRateLimiter\x12S\n" +
	"\n" +
	"CheckLimit\x12!.ratelimiter.v1.CheckLimitRequest\x1a\".ratelimiter.v1.CheckLimitResponse\x12\\\n" +
	"\x0fCheckLimitBatch\x12!.ratelimiter.v1.CheckLimitRequest\x1a\".ratelimiter.v1.CheckLimitResponse(\x010\x01BEZCgithub.com/varunsalian/ratelimiter/api/ratelimiter/v1;ratelimiterv1b\x06proto3"

var (
	file_api_ratelimiter_v1_ratelimiter_proto_rawDescOnce sync.Once
	file_api_ratelimiter_v1_ratelimiter_proto_rawDescData []byte
)

func file_api_ratelimiter_v1_ratelimiter_proto_rawDescGZIP() []byte {
	file_api_ratelimiter_v1_ratelimiter_proto_rawDescOnce.Do(func() {
		file_api_ratelimiter_v1_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ratelimiter_v1_ratelimiter_proto_rawDesc), len(file_api_ratelimiter_v1_ratelimiter_proto_rawDesc)))
	})
	return file_api_ratelimiter_v1_ratelimiter_proto_rawDescData
}

var file_api_ratelimiter_v1_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ratelimiter_v1_ratelimiter_proto_goTypes = []any{
	(*CheckLimitRequest)(nil),  // 0: ratelimiter.v1.CheckLimitRequest
	(*CheckLimitResponse)(nil), // 1: ratelimiter.v1.CheckLimitResponse
}
var file_api_ratelimiter_v1_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.v1.RateLimiter.CheckLimit:input_type -> ratelimiter.v1.CheckLimitRequest
	0, // 1: ratelimiter.v1.RateLimiter.CheckLimitBatch:input_type -> ratelimiter.v1.CheckLimitRequest
	1, // 2: ratelimiter.v1.RateLimiter.CheckLimit:output_type -> ratelimiter.v1.CheckLimitResponse
	1, // 3: ratelimiter.v1.RateLimiter.CheckLimitBatch:output_type -> ratelimiter.v1.CheckLimitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ratelimiter_v1_ratelimiter_proto_init() }
func file_api_ratelimiter_v1_ratelimiter_proto_init() {
	if File_api_ratelimiter_v1_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ratelimiter_v1_ratelimiter_proto_rawDesc), len(file_api_ratelimiter_v1_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ratelimiter_v1_ratelimiter_proto_goTypes,
		DependencyIndexes: file_api_ratelimiter_v1_ratelimiter_proto_depIdxs,
		MessageInfos:      file_api_ratelimiter_v1_ratelimiter_proto_msgTypes,
	}.Build()
	File_api_ratelimiter_v1_ratelimiter_proto = out.File
	file_api_ratelimiter_v1_ratelimiter_proto_goTypes = nil
	file_api_ratelimiter_v1_ratelimiter_proto_depIdxs = nil
}
