// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/ratelimiter/v1/ratelimiter.proto

package ratelimiterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimiter_CheckLimit_FullMethodName      = "/ratelimiter.v1.RateLimiter/CheckLimit"
	RateLimiter_CheckLimitBatch_FullMethodName = "/ratelimiter.v1.RateLimiter/CheckLimitBatch"
)

// RateLimiterClient is the client API for RateLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RateLimiter exposes the core rate limit check operations.
type RateLimiterClient interface {
	// CheckLimit performs a single atomic rate limit check.
	//
	// Always returns OK status. Inspect the response body for the result:
	//
	//	allowed=true  → request is permitted
	//	allowed=false → request is denied; retry_after_ms tells the caller when to retry
	//
	// Non-OK status codes indicate service-level failures:
	//
	//	NOT_FOUND        → no plan configured for the tenant+key pair
	//	INVALID_ARGUMENT → empty tenant_id or key, or misconfigured plan
	//	UNAVAILABLE      → backing store unreachable and plan is fail-closed
	CheckLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error)
	// CheckLimitBatch streams sequential rate limit checks over a single connection.
	//
	// Designed for hierarchical limits (e.g. per-user AND per-tenant): the client
	// sends check N, reads the response, and decides whether to send check N+1.
	// This allows client-side early exit — if check 1 is denied, check 2 is never
	// sent and its counter is never touched.
	//
	// Each check is individually atomic; the two checks are NOT atomic with respect
	// to each other. If check 1 succeeds and check 2 fails or errors, check 1's
	// token is permanently consumed. See service docs for the fairness implications.
	//
	// Stream lifecycle:
	//   - Client sends requests and reads responses in lockstep or pipelined.
	//   - Client closes the send side (half-close) when done.
	//   - Any non-OK status from the server closes the stream immediately.
	CheckLimitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CheckLimitRequest, CheckLimitResponse], error)
}

type rateLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterClient(cc grpc.ClientConnInterface) RateLimiterClient {
	return &rateLimiterClient{cc}
}

func (c *rateLimiterClient) CheckLimit(ctx context.Context, in *CheckLimitRequest, opts ...grpc.CallOption) (*CheckLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckLimitResponse)
	err := c.cc.Invoke(ctx, RateLimiter_CheckLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) CheckLimitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CheckLimitRequest, CheckLimitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RateLimiter_ServiceDesc.Streams[0], RateLimiter_CheckLimitBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CheckLimitRequest, CheckLimitResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RateLimiter_CheckLimitBatchClient = grpc.BidiStreamingClient[CheckLimitRequest, CheckLimitResponse]

// RateLimiterServer is the server API for RateLimiter service.
// All implementations must embed UnimplementedRateLimiterServer
// for forward compatibility.
//
// RateLimiter exposes the core rate limit check operations.
type RateLimiterServer interface {
	// CheckLimit performs a single atomic rate limit check.
	//
	// Always returns OK status. Inspect the response body for the result:
	//
	//	allowed=true  → request is permitted
	//	allowed=false → request is denied; retry_after_ms tells the caller when to retry
	//
	// Non-OK status codes indicate service-level failures:
	//
	//	NOT_FOUND        → no plan configured for the tenant+key pair
	//	INVALID_ARGUMENT → empty tenant_id or key, or misconfigured plan
	//	UNAVAILABLE      → backing store unreachable and plan is fail-closed
	CheckLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error)
	// CheckLimitBatch streams sequential rate limit checks over a single connection.
	//
	// Designed for hierarchical limits (e.g. per-user AND per-tenant): the client
	// sends check N, reads the response, and decides whether to send check N+1.
	// This allows client-side early exit — if check 1 is denied, check 2 is never
	// sent and its counter is never touched.
	//
	// Each check is individually atomic; the two checks are NOT atomic with respect
	// to each other. If check 1 succeeds and check 2 fails or errors, check 1's
	// token is permanently consumed. See service docs for the fairness implications.
	//
	// Stream lifecycle:
	//   - Client sends requests and reads responses in lockstep or pipelined.
	//   - Client closes the send side (half-close) when done.
	//   - Any non-OK status from the server closes the stream immediately.
	CheckLimitBatch(grpc.BidiStreamingServer[CheckLimitRequest, CheckLimitResponse]) error
	mustEmbedUnimplementedRateLimiterServer()
}

// UnimplementedRateLimiterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimiterServer struct{}

func (UnimplementedRateLimiterServer) CheckLimit(context.Context, *CheckLimitRequest) (*CheckLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckLimit not implemented")
}
func (UnimplementedRateLimiterServer) CheckLimitBatch(grpc.BidiStreamingServer[CheckLimitRequest, CheckLimitResponse]) error {
	return status.Error(codes.Unimplemented, "method CheckLimitBatch not implemented")
}
func (UnimplementedRateLimiterServer) mustEmbedUnimplementedRateLimiterServer() {}
func (UnimplementedRateLimiterServer) testEmbeddedByValue()                     {}

// UnsafeRateLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServer will
// result in compilation errors.
type UnsafeRateLimiterServer interface {
	mustEmbedUnimplementedRateLimiterServer()
}

func RegisterRateLimiterServer(s grpc.ServiceRegistrar, srv RateLimiterServer) {
	// If the following call panics, it indicates UnimplementedRateLimiterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimiter_ServiceDesc, srv)
}

func _RateLimiter_CheckLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).CheckLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_CheckLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).CheckLimit(ctx, req.(*CheckLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_CheckLimitBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RateLimiterServer).CheckLimitBatch(&grpc.GenericServerStream[CheckLimitRequest, CheckLimitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RateLimiter_CheckLimitBatchServer = grpc.BidiStreamingServer[CheckLimitRequest, CheckLimitResponse]

// RateLimiter_ServiceDesc is the grpc.ServiceDesc for RateLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratelimiter.v1.RateLimiter",
	HandlerType: (*RateLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckLimit",
			Handler:    _RateLimiter_CheckLimit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckLimitBatch",
			Handler:       _RateLimiter_CheckLimitBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/ratelimiter/v1/ratelimiter.proto",
}
